course = "      Python programming     "
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.rstrip())
print(course.find("pro"))
print(course.find("Pro"))
print(course.replace("o", "-"))
print("Programming" in course)
print("Programming" not in course)
